name: Deploy
on: {push: {branches: [main]}}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sed -i "s|__KJA671_SUGAR__|${{ secrets.KJA671_SUGAR }}|g" js/discord.js
      - uses: peaceiris/actions-gh-pages@v3
        with: { github_token: ${{ secrets.GITHUB_TOKEN }}, publish_dir: ./ }
